
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xbb\x82$\xf8\xa8\xe9x}x$\x86 ~M\x96\x8e'

_lr_action_items = {'NODEINFO':([0,],[16,]),'FVNAME':([20,21,44,],[34,34,34,]),'NUMBER':([22,],[36,]),'HAVE':([1,2,14,15,17,28,29,30,38,39,],[-17,21,-4,-6,27,-19,-18,-16,-3,-5,]),'COMMENT':([0,],[3,]),'SET':([0,],[4,]),'FDNAME':([32,34,],[46,48,]),')':([54,],[56,]),'(':([13,],[23,]),',':([1,14,15,20,21,28,29,31,37,42,44,45,46,47,48,50,51,],[19,24,25,-13,-13,-19,-18,44,49,52,-13,-9,-11,-10,-12,-24,-25,]),'GENERAL':([0,],[5,]),'BRAIN':([0,],[6,]),'STRNAME':([18,23,49,],[28,37,54,]),'PARNAME':([4,],[22,]),'CLEAR':([0,],[8,]),'PRINT_COMMENT':([0,],[9,]),'HAS':([1,2,14,15,17,28,29,30,38,39,],[-17,20,-4,-6,26,-19,-18,-16,-3,-5,]),'MATCH':([0,],[10,]),'HISTORY':([0,],[11,]),'QUIT':([0,],[12,]),'COMPARE':([0,],[13,]),'NAME':([0,18,20,21,24,25,26,27,32,34,40,44,52,],[14,29,32,32,14,14,40,40,45,47,50,32,40,]),'OBJNAME':([0,24,25,40,],[15,15,15,51,]),'$end':([3,5,6,7,8,9,10,11,12,16,20,21,31,33,35,36,41,42,43,44,45,46,47,48,50,51,53,55,56,],[-1,-30,-31,0,-32,-2,-29,-27,-33,-28,-13,-13,-8,-14,-15,-34,-20,-23,-21,-13,-9,-11,-10,-12,-24,-25,-7,-22,-26,]),'STRUCTURE':([0,19,],[18,18,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'featurepair':([20,21,44,],[31,31,31,]),'structurebase':([0,19,],[1,1,]),'roleplus':([26,27,52,],[41,43,55,]),'featurepairplus':([20,21,44,],[33,35,53,]),'objectplus':([0,24,25,],[2,38,39,]),'role':([26,27,52,],[42,42,42,]),'statement':([0,],[7,]),'structureplus':([0,19,],[17,30,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('statement',1,'p_statement_comment','Induce.py',125),
  ('statement',1,'p_statement_print_comment','Induce.py',130),
  ('objectplus',3,'p_objectplus','Induce.py',135),
  ('objectplus',1,'p_objectplus','Induce.py',136),
  ('objectplus',3,'p_objectplus','Induce.py',137),
  ('objectplus',1,'p_objectplus','Induce.py',138),
  ('featurepairplus',3,'p_featurepairplus','Induce.py',149),
  ('featurepairplus',1,'p_featurepairplus','Induce.py',150),
  ('featurepair',2,'p_featurepair','Induce.py',157),
  ('featurepair',2,'p_featurepair','Induce.py',158),
  ('featurepair',2,'p_featurepair','Induce.py',159),
  ('featurepair',2,'p_featurepair','Induce.py',160),
  ('featurepair',0,'p_featurepair','Induce.py',161),
  ('statement',3,'p_statement','Induce.py',167),
  ('statement',3,'p_statement','Induce.py',168),
  ('structureplus',3,'p_structureplus','Induce.py',174),
  ('structureplus',1,'p_structureplus','Induce.py',175),
  ('structurebase',2,'p_structurebase','Induce.py',182),
  ('structurebase',2,'p_structurebase','Induce.py',183),
  ('statement',3,'p_structure_statement','Induce.py',189),
  ('statement',3,'p_structure_statement','Induce.py',190),
  ('roleplus',3,'p_roleplus','Induce.py',195),
  ('roleplus',1,'p_roleplus','Induce.py',196),
  ('role',2,'p_role','Induce.py',203),
  ('role',2,'p_role','Induce.py',204),
  ('statement',6,'p_compare_objects','Induce.py',209),
  ('statement',1,'p_history','Induce.py',221),
  ('statement',1,'p_nodeinfo','Induce.py',227),
  ('statement',1,'p_match','Induce.py',233),
  ('statement',1,'p_general','Induce.py',239),
  ('statement',1,'p_brain','Induce.py',245),
  ('statement',1,'p_clear','Induce.py',255),
  ('statement',1,'p_quit','Induce.py',265),
  ('statement',3,'p_set','Induce.py',269),
]
