
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '.?]\x7fn#\x13\x84k\xef)$ \xae \x18'

_lr_action_items = {'NODEINFO':([0,],[15,]),'FVNAME':([19,20,41,],[32,32,32,]),'HAVE':([1,2,13,14,16,26,27,28,35,36,],[-17,20,-4,-6,25,-19,-18,-16,-3,-5,]),'COMMENT':([0,],[3,]),'FDNAME':([30,32,],[43,45,]),')':([51,],[53,]),'(':([12,],[21,]),',':([1,13,14,19,20,26,27,29,34,39,41,42,43,44,45,47,48,],[18,22,23,-13,-13,-19,-18,41,46,49,-13,-9,-11,-10,-12,-24,-25,]),'GENERAL':([0,],[4,]),'BRAIN':([0,],[5,]),'STRNAME':([17,21,46,],[26,34,51,]),'$end':([3,4,5,6,7,8,9,10,11,15,19,20,29,31,33,38,39,40,41,42,43,44,45,47,48,50,52,53,],[-1,-30,-31,0,-32,-2,-29,-27,-33,-28,-13,-13,-8,-14,-15,-20,-23,-21,-13,-9,-11,-10,-12,-24,-25,-7,-22,-26,]),'CLEAR':([0,],[7,]),'PRINT_COMMENT':([0,],[8,]),'HAS':([1,2,13,14,16,26,27,28,35,36,],[-17,19,-4,-6,24,-19,-18,-16,-3,-5,]),'MATCH':([0,],[9,]),'HISTORY':([0,],[10,]),'QUIT':([0,],[11,]),'COMPARE':([0,],[12,]),'NAME':([0,17,19,20,22,23,24,25,30,32,37,41,49,],[13,27,30,30,13,13,37,37,42,44,47,30,37,]),'OBJNAME':([0,22,23,37,],[14,14,14,48,]),'STRUCTURE':([0,18,],[17,17,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'featurepair':([19,20,41,],[29,29,29,]),'structurebase':([0,18,],[1,1,]),'roleplus':([24,25,49,],[38,40,52,]),'featurepairplus':([19,20,41,],[31,33,50,]),'objectplus':([0,22,23,],[2,35,36,]),'role':([24,25,49,],[39,39,39,]),'statement':([0,],[6,]),'structureplus':([0,18,],[16,28,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('statement',1,'p_statement_comment','Induce.py',122),
  ('statement',1,'p_statement_print_comment','Induce.py',127),
  ('objectplus',3,'p_objectplus','Induce.py',132),
  ('objectplus',1,'p_objectplus','Induce.py',133),
  ('objectplus',3,'p_objectplus','Induce.py',134),
  ('objectplus',1,'p_objectplus','Induce.py',135),
  ('featurepairplus',3,'p_featurepairplus','Induce.py',146),
  ('featurepairplus',1,'p_featurepairplus','Induce.py',147),
  ('featurepair',2,'p_featurepair','Induce.py',154),
  ('featurepair',2,'p_featurepair','Induce.py',155),
  ('featurepair',2,'p_featurepair','Induce.py',156),
  ('featurepair',2,'p_featurepair','Induce.py',157),
  ('featurepair',0,'p_featurepair','Induce.py',158),
  ('statement',3,'p_statement','Induce.py',164),
  ('statement',3,'p_statement','Induce.py',165),
  ('structureplus',3,'p_structureplus','Induce.py',171),
  ('structureplus',1,'p_structureplus','Induce.py',172),
  ('structurebase',2,'p_structurebase','Induce.py',179),
  ('structurebase',2,'p_structurebase','Induce.py',180),
  ('statement',3,'p_structure_statement','Induce.py',186),
  ('statement',3,'p_structure_statement','Induce.py',187),
  ('roleplus',3,'p_roleplus','Induce.py',192),
  ('roleplus',1,'p_roleplus','Induce.py',193),
  ('role',2,'p_role','Induce.py',200),
  ('role',2,'p_role','Induce.py',201),
  ('statement',6,'p_compare_objects','Induce.py',206),
  ('statement',1,'p_history','Induce.py',218),
  ('statement',1,'p_nodeinfo','Induce.py',224),
  ('statement',1,'p_match','Induce.py',230),
  ('statement',1,'p_general','Induce.py',236),
  ('statement',1,'p_brain','Induce.py',242),
  ('statement',1,'p_clear','Induce.py',252),
  ('statement',1,'p_quit','Induce.py',262),
]
